version:  '3.9'

services:

  db:
    platform: linux/amd64
    container_name: pg_db
    hostname: pg_db
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: my_DB
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=ru_RU.UTF-8 --lc-ctype=ru_RU.UTF-8 --lc-messages=ru_RU.UTF-8 --lc-monetary=ru_RU.UTF-8 --lc-numeric=ru_RU.UTF-8 --lc-time=ru_RU.UTF-8'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  pgadmin:
    platform: linux/amd64
    container_name: pgadmin
    hostname: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: noemail@noemail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

#connect to postre from pgadmin by hostname
